# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScreenRotationDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'
  pod 'FLEX', '4.4.0', :configurations => ['Debug']

  # Pods for ScreenRotationDemo

end
