# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RunLoopInterviewQuestion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RunLoopInterviewQuestion
  pod 'FPSLabel'
  pod 'AFNetworking'
end
